### ISSUE TITLE
Is there some problem with the time_stamp in v2018??

### ISSUE THREAD

**Issue by tjrone** [alibaba/clusterdata#52]
8 days has 691200 second, and in machine_usage.csv, a mahcine's time_stamp is exactly from 0 to 691190. 
But, it's strange that most of the containers in container_usage.csv has bigger time_stamp than 691200. For example c_5911(container_id = 5911), it's time_stamp is from 86400 to 777590. 
And I found that 777590-86400=691190=8 days
It means that the information of this container is from day 2 to day 9.
why there is no information about the container in day 1 ?
And why there is an extra day(day 9) for only container information ?
So, should we change the time_stamp of container_usage???
@HaiyangDING

**Comment by HaiyangDING** [comment]
Hi, thanks for pointing this out.

The time_stanmp itself is correct (i.e. the difference from time-zero), that is: some metrics are of day 1 to day 8 and some are of day 2 to day 9. This is caused by a bug in cleaning the data during the release, for which I am sorry. However, you still get 7-day of metrics that is somehow better aligned.

**Comment by tjrone** [comment]
Thanks for your reply.

**Comment by xshaun** [comment]
@HaiyangDING  Could we suppose day1-8 is the same period as day2-9 ?  this is just bug on adjustment? Thanks

**Comment by HaiyangDING** [comment]
> @HaiyangDING Could we suppose day1-8 is the same period as day2-9 ? this is just bug on adjustment? Thanks

No, we cannot.
