### ISSUE TITLE
Time illegal in container_usage.csv

### ISSUE THREAD

**Issue by GitHubOfCui** [alibaba/clusterdata#54]
I found in container_usage.csv,there is no one record's timestamp located in day 1 but a lot of record in day 9,is this a mistake?.

**Comment by HaiyangDING** [comment]
Hi, this is a known issue caused during data cleaning as I have confirmed in [issue#52] (https://github.com/alibaba/clusterdata/issues/52). 

The time_stanmp itself is correct (i.e. the difference from time-zero), that is: some metrics are of day 1 to day 8 and some are of day 2 to day 9. This is caused by a bug in cleaning the data during the release, for which I am sorry. However, you still get 7-day of metrics that is somehow better aligned.
